DROP TABLE Doacoes

CREATE TABLE Doacoes
(
   ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
   ID_Doador INT NOT NULL,
   ID_Funcionario INT NOT NULL,
   Data_Doacao TIMESTAMP
)ENGINE MyIsam


CREATE TABLE Doacoes_Items
(
   ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
   ID_Doacao INT NOT NULL,
   ID_Livro INT NOT NULL,
   Quantidade TINYINT
)ENGINE MyIsam